version: '3.7'

services:
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - osnet

  dashboards:
    build: .
    container_name: fdl-ui
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - 5601:5601
    depends_on:
      - opensearch
    networks:
      - osnet

networks:
  osnet:
    driver: bridge
